# Created by: Thomas Steen Rasmussen <thomas@gibfest.dk>
# $FreeBSD$

PORTNAME=	certgrinderd
PORTVERSION=	0.13.1
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	thomas@gibfest.dk
COMMENT=	The server part of the certgrinder project. use with the 'certgrinder' client package

LICENSE=	BSD3CLAUSE

USES=		python:3.7+ # 3.7, 3.8
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
