# Created by: Thomas Steen Rasmussen <thomas@gibfest.dk>
# $FreeBSD$

PORTNAME=	certgrinder
PORTVERSION=	0.13.1
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	thomas@gibfest.dk
COMMENT=	The client part of the certgrinder project. use with 'certgrinderd' package on the serverside

# LICENSE=	BSD License # Ensure this is valid! See ${PORTSDIR}/Mk/bsd.licenses.db.mk.

USES=		python:3.7+ # 3.7, 3.8
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
